export const HOMES = [
    {
        name: 'Family House',
        location: 'Switherland',
        price: 64000000,
        space: 200 ,
        rooms: 5,
        image: 'https://i.ibb.co/7Yh3dxG/house-6.jpg',
        flag: ' 🇨🇭 ',
    },
    {
        name: 'Modern Glass Villa',
        location: 'Canada',
        price: 12000000,
        space: 220 ,
        rooms: 7,
        image: 'https://i.ibb.co/JkXv1dP/house-3.jpg',
        flag:  '🇨🇦' ,
    },
    {
        name: 'Cozy Country House',
        location: 'USA',
        price: 4500000,
        space: 300 ,
        rooms: 4,
        image: 'https://i.ibb.co/yy6Q9k8/house-1.jpg',
        flag:  '🇺🇸' ,
    },
    {
        name: 'Fancy House',
        location: 'Egypt',
        price: 8500000,
        space: 450 ,
        rooms: 5,
        image: 'https://i.ibb.co/N7tWCfb/house-5.jpg',
        flag:  '🇪🇬',
    },
    {
        name: 'Elegant Big House',
        location: 'UK',
        price: 7000000,
        space: 120 ,
        rooms: 3,
        image: 'https://i.ibb.co/QctW005/house-4.jpg',
        flag:  '🇬🇧' ,
    }, 
    {
        name:  'Modern House',
        location: 'Italy',
        price: 9500000,
        space: 90 ,
        rooms: 8,
        image: 'https://i.ibb.co/ZzBJ94x/house-2.jpg',
        flag:  '🇮🇹' ,
    },
]